enum ORDER_TYPE {
  BUY = "BUY",
  SELL = "SELL",
}

type PortfolioItem = {
  name: string;
  ticker: string;
  units: number;
  img: string;
  avgOpen: number;
  invested: number;
  pln: number;
  orderType: ORDER_TYPE;
  id: string;
};

export const items: PortfolioItem[] = [
  {
    id: "xxx",
    name: "Intel",
    ticker: "INTC",
    units: 2.12,
    img: "assets/images/stocks/intc_0068B5.svg",
    avgOpen: 35.36,
    invested: 100,
    pln: 1.88,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "zzzz",
    name: "Microsoft",
    ticker: "MSFT",
    units: 0.344,
    img: "assets/images/stocks/msft_f7f77f7.svg",
    avgOpen: 289.96,
    invested: 100,
    pln: 0.23,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "xxx",
    name: "Intel",
    ticker: "INTC",
    units: 2.12,
    img: "assets/images/stocks/intc_0068B5.svg",
    avgOpen: 35.36,
    invested: 100,
    pln: 1.88,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "zzzz",
    name: "Microsoft",
    ticker: "MSFT",
    units: 0.344,
    img: "assets/images/stocks/msft_f7f77f7.svg",
    avgOpen: 289.96,
    invested: 100,
    pln: 0.23,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "xxx",
    name: "Intel",
    ticker: "INTC",
    units: 2.12,
    img: "assets/images/stocks/intc_0068B5.svg",
    avgOpen: 35.36,
    invested: 100,
    pln: 1.88,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "zzzz",
    name: "Microsoft",
    ticker: "MSFT",
    units: 0.344,
    img: "assets/images/stocks/msft_f7f77f7.svg",
    avgOpen: 289.96,
    invested: 100,
    pln: 0.23,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "xxx",
    name: "Intel",
    ticker: "INTC",
    units: 2.12,
    img: "assets/images/stocks/intc_0068B5.svg",
    avgOpen: 35.36,
    invested: 100,
    pln: 1.88,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "zzzz",
    name: "Microsoft",
    ticker: "MSFT",
    units: 0.344,
    img: "assets/images/stocks/msft_f7f77f7.svg",
    avgOpen: 289.96,
    invested: 100,
    pln: 0.23,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "xxx",
    name: "Intel",
    ticker: "INTC",
    units: 2.12,
    img: "assets/images/stocks/intc_0068B5.svg",
    avgOpen: 35.36,
    invested: 100,
    pln: 1.88,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "zzzz",
    name: "Microsoft",
    ticker: "MSFT",
    units: 0.344,
    img: "assets/images/stocks/msft_f7f77f7.svg",
    avgOpen: 289.96,
    invested: 100,
    pln: 0.23,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "xxx",
    name: "Intel",
    ticker: "INTC",
    units: 2.12,
    img: "assets/images/stocks/intc_0068B5.svg",
    avgOpen: 35.36,
    invested: 100,
    pln: 1.88,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "zzzz",
    name: "Microsoft",
    ticker: "MSFT",
    units: 0.344,
    img: "assets/images/stocks/msft_f7f77f7.svg",
    avgOpen: 289.96,
    invested: 100,
    pln: 0.23,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "xxx",
    name: "Intel",
    ticker: "INTC",
    units: 2.12,
    img: "assets/images/stocks/intc_0068B5.svg",
    avgOpen: 35.36,
    invested: 100,
    pln: 1.88,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "zzzz",
    name: "Microsoft",
    ticker: "MSFT",
    units: 0.344,
    img: "assets/images/stocks/msft_f7f77f7.svg",
    avgOpen: 289.96,
    invested: 100,
    pln: 0.23,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "xxx",
    name: "Intel",
    ticker: "INTC",
    units: 2.12,
    img: "assets/images/stocks/intc_0068B5.svg",
    avgOpen: 35.36,
    invested: 100,
    pln: 1.88,
    orderType: ORDER_TYPE.BUY,
  },
  {
    id: "zzzz",
    name: "Microsoft",
    ticker: "MSFT",
    units: 0.344,
    img: "assets/images/stocks/msft_f7f77f7.svg",
    avgOpen: 289.96,
    invested: 100,
    pln: 0.23,
    orderType: ORDER_TYPE.BUY,
  },
];
